### ISSUE TITLE
Consider adding OpenVR libs as a git submodule?

### ISSUE THREAD

**Issue by stephenohair** [kotlin-graphics/openvr#2]
Very minor but might take the hassle out of pushing the new binaries each time they're updated by Valve/OpenVR.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by elect86** [comment]
It's an interesting idea.. 

But I lack experience with git submodules, do you have some?

I also may look into Gradle if it's possible to do that

**Comment by stephenohair** [comment]
I looked further into this. I found two issues with using git submodules.
* when recursively checking out the parent git project each submodule is checked out with a cascading depednecy effect.
* should one of those dependent repos be removed by the author at the chosen branch/tag then the checkout of parent will fail

I've put an issue in to openvr valvesoftware/openvr#764 to see if they'd consider migrating their binaries to conan-center. We could then just point gradle to the repo and only need to bump up version numbers to update sdk versions.

**Comment by elect86** [comment]
Yeah, I recall one blog article talking about using git submodules only under some specific conditions (~constraints)

Hopefully I'll play with Gradle sooner

Thanks for your efforts, though

**Comment by elect86** [comment]
Ps: the blog was the [official one](https://blog.github.com/2016-02-01-working-with-submodules/), you can read the notes I meant at the end

Pps: playing with this [one](https://github.com/michel-kraemer/gradle-download-task) at the moment

**Comment by stephenohair** [comment]
Nice job with using gradle for downloading the dependencies. I once had to do something similar for android library dependencies a long time ago.

**Comment by elect86** [comment]
Thanks Stephen..

Although I left out Mac Os because I couldn't find a way to recursively download that (it"s based on multiple directories), but I dont think we have an user base for that.. 

I'll look into that in the long period though
